import React from 'react';
import "./Belief.css";

export default function Beliefs() {
    return (
        <section id="belief" className="belief">
        <div className="img" data-aos="fade-down">
            <img src="https://res.cloudinary.com/lawfirm1000/image/upload/v1593830161/bible_tqutcw.jpg" alt="" />
        </div>
        <div className="container text">
            <h1  data-aos="fade-right" data-aos-delay="100">What We Believe</h1>
            <ul  data-aos="fade-up" data-aos-delay="200">
            <li><p>That <strong>the Holy Bible</strong>, consisting of 39 books of the Old Testament and 27 books of the New Testament, is the inspired Word of God. We take the bible as final authority in all matters concerning Christian conduct and work; it is the only standard of truth and the only model of pure religion. 2Tim. 3:16:17, pro. 30:5, 6; Rev. 22: 18, 19. </p></li>
            <li><p>That <strong>the Godhead</strong> consists of three separate, distinct, and recognizable personalities and qualities perfectly united in one. The Father, the Son, the Holy ‘Spirit are different Persons in the Godhead not merely three names for one Person Mat. 3:16-17; 2 cor. 13:14; Mat. 18-25; Rom. 1:4; 1 Cor. 15:3, 4. </p></li>
            <li><p><strong>The Virgin birth</strong> of Jesus Christ, the only begotten Son of God. The Crucifixion, death, burial and bodily resurrection of Jesus Christ. Is.7:14; Matt. 18-25, Rom. 1:4:1Cor. 15:34.</p></li>
            <li><p><strong>The total depravity,</strong> sinfulness and guilt of all humans since the fall, rendering them subject to God’s wrath and condemnation. Ps 51:5; Job 14:4, Rom. 3:23, 4, 12, 17; Mark 7. 21-23; Eph. 2:1. </p></li>
            <li><p>That <strong>Repentance </strong>is a complete turning away from all sins, its deceitful pleasures and that it is required from every sinner before he can truly and effectively believe in Jesus with saving faith. Pro. 28:113; is. 55:7; Ezk 18:21-23; mark 1:15 Luke 24:46; Acts 2:38; 20:20, 21:2 Cor. 7:10; Heb. 6:1-3.  </p></li>
            <li><p>That <strong>Restitution </strong> is making amends for wrongs done against our fellow men, restoring stolen things to their rightful owners,  paying debts, giving back where one has defrauded, making confessions to the offended and apologizing to those slandered so as to have a conscience void of  offence toward God man. Gen. 20:1-8, 14-18; Exo. 22:1-7; Lev. 6:1-7; Num. 5:6- 8:2sam. 12:1-6; pro. 6:31; Ezk. 33: 14-16; Mat. 5:23-24; Luke 19: 8,9; Acts 23; 1-5; 24; 16; Jam. 4:17;5:6. </p></li>
            <li><p>That <strong>Justification</strong> is the act of God’s grace whereby one receives forgiveness and remission of sins and is counted righteous before god, through faith and the atoning blood of Jesus, standing before god as though he had never sinned. Ps. 32:1, 2; Is. 1:18; Micah 7:19; John 3:3-8; Acts 13:30, 39; 4:6-16; 5:1,2:2 cor. 5 cor. 5:11, 17-21; Gal. 2:16; Eph. 2:8, 9, Tit. 3:5: 1 Pet. 1:23 </p></li>
            <li><p>That <strong>Water Baptism </strong>is essential to our obedience after reconciliation with God. Water baptism in one immersion (not three) ‘in the name of the father and Son and the Holy Spirit”, as Jesus commanded –Mat. 3:13-17; 28:19; Mark 16:15, 116; Acts 2:38, 8:38, 39; 19; 1-6; Rom. 6: 4, 5. </p></li>
            <li><p>That <strong>the Lord’s Supper </strong>was instituted by Jesus Christ so that all believers (all members of the family of God) might partake thereof regularly, to ‘remember the Lord till He comes”. The emblems used are ‘unleavened bread’ and the juice of ‘fruit of the vine’. Anyone who eats and drinks unworthily brings “damnation”, punishment, and chastisement upon himself. Mat. 26:29: Luke 22:17-20: 1Cor 11:23-30. </p></li>
            <li><p>That <strong>the baptism in the Holy Spirit</strong> is the enduement of power from on high upon the believer. It is ‘the promise of the Father’ and when one receives this ‘gift of the Spirit’ it is accompanied by the initial evidence of speaking a language unlearned previously, referred to as speaking in tongues as the Spirit gives utterance. Matt 3:11; Acts 1:8, Luke 3:16; 24:49; Jn 1:30-33; 7:37-39; 14; 16, 17,26; 16:11,12-15, Acts 1:5-8 2:1-18; 10:44-46; 19;1-6 Mark 16:17.</p></li>
            <li><p>That <strong>Redemption </strong>from the curse of the law, healing of sickness and disease as well as continued health is provided for a people through the sacrificial death of Jesus Christ. Exo 15:26; Deu. 7:15; Ps. 103; 1-5; Pro. 4:20-22; Is. 53; 4, 5; Mat. 8:16, 17 1Pet 2:24; Mark 16:15-18, Luke 13:16 Jn. 14:12-14; 10:10; Acts 10:38; Jam. 5:14-11-16;  Jn. 3:8 3 Jn. 2; Gal 3:13-14 </p></li>
            <li><p>That <strong>Personal Evangelism</strong> is a God given and God-ordained ministry for every believer, Jesus commanded and requires every believer to be a compassionate and fruitful soul winner, bringing others to Christ. Mat. 28: 19, 20; Mark 16:15; Luke 24:46-49; Jn. 17:18, Acts 1:8; Ps. 126:5,6; pro 11:30; Dan. 12:3 </p></li>
            <li><p>That <strong>Marriage </strong>is binding for life. Monogamy is the uniform teaching of the bible. Polygamy is contrary to God’s perfect will and institution. Also, under the New Testament dispensation, no one has a right to divorce and remarry while the first companion lives. When a person becomes converted, necessary restitution, on this line, must be done without delay if he/she married wrongly. Gen. 2:24; Deut. 7:1-4; Job 23:11-13; 2Cor. 6:114-18; Pro. 31:10-31; Mal. 2:14, 15; Rom. 7:2 Eph. 5:31-33; Mat. 5:31, 32; 19:3-9; Mark 10:2-21, Luke 16:18; Jn. 4:15-19</p></li>
            <li><p>That <strong>the Rapture </strong>(commonly referred to as the first phase or stage of the SECOND COMING OF CHRIST) is the catching away from the earth, of all living saints and all who died in the lord. The rapture will take placed before the Great Tribulation and can happen any time from now. “In a twinkling of an eye: without a moment’s warning, “the trumpet shall sound” and  the dead in Christ shall rise first; then we which are alive and remain shall be caught up together  with them in the clouds, to meet the Lord”. Jn. 14 1-3; Luke 21:34-36; 1 Cor. 15:51-58; 1 Thess. 4:13-18; 5:4-9; 2 Thess. 2:5-7; Phi. 3:11, 20, 21; 1Jn. 3: 1-3</p></li>
            <li><p>That <strong>the Resurrection of the Dead</strong> is taught in the bible as clearly as the immortality of the soul. Every individual who has ever lived will be resurrected, some to honour and glory and others to everlasting shame and contempt. Job. 19:25, 27; Ps 71:20; I1. 26; 19; Dan 12:2 in. 5:28-29; Heb. 6:1-2, Phi. 3:8-11; Rev. 20:4-13.</p></li>
            <li><p>That <strong>the Great Tribulation</strong> will occur after Rapture and will be a time of terrible suffering on earth. It is also referred to as the time of ‘Jacob’s trouble’ Matt 24:21, 22, 29; Rev 9:16, Mark 13:19; 2Thess. 2:3-12; Rev. 13. During this time, the Antichrist will take possession of this world for a reign of terror. He will not be a system or organization but a person a supernatural, diabolical being, in the form of a man who will blaspheme and proclaim himself as God. Dan. 8:23-25; 2 Thess. 2:7-12; Rev. 13:1-10.</p></li>
            <li><p>That <strong>the second Coming of Christ</strong> will be just as literal and visible as his going away, and He is coming to execute judgment upon the ungodly. He will also, then, set up his kingdom and reigns on this present earth for a thousand years. Zec. 14:3.4; Mat. 25:31-46; 26:64; Mark 13:24-37; 2 Thess. 1:7-10; 2:8; Jude 14:15.</p></li>
            <li><p>That <strong>Christ’s Millennial Reign</strong> is the 1000 years literal reign of Jesus on earth. This will be ushered in by the coming of Jesus back to the earth with ‘ten thousands of His saints’. At this time, He will judge the nations that will dwell upon the face of the earth. Jude 14-15, 2Thess 1:7-11. During this time, the devil will be bound. Rev20:2-3. It will be a reign of peace and blessing. Is. 11:6-9, 2:2-4, Zec 14:9-20.</p></li>
            <li><p>That <strong>the Great White Throne Judgment</strong> is when God finally judges all (the living and the dead, small and great) who have ever lived on the face of the earth, according to their works. This after the millennium, at this time, the final judgment known as the Great White Judgment will be held. People from all ages, who have not yet been judged, will stand before God at this time. The devil and his angels are judged at this time also and sent to the lake of fire forever. –Dan. 12:2, 3; Mat. 10:15; 11:21, 24; 12:41, 42; jn. 5: 28-29; Rom. 2:15, 16; 14:12, 2 pet. 2:9; Jude 6: 1 cor 6:1-4; Acts 10:42; Rev. 20:11-15.</p></li>
            <li><p>That <strong>the New Heaven and New Earth</strong> "Wherein dwelleth righteousness’ will be made by God and the redeemed shall dwell with God forever. This present earth, which has been polluted by sin, will pass away after the Great White Throne Judgment. Ps. 102; 25, 26; Is 51:6:65:17; Mat. 5:19, 24:35; 2 Pet. 3; 10-13; Rev. 21:1 No unclean thing will be there. We shall know one another our knowledge having been perfected. There will be no more waiting upon anything. There will be no more night; the glory of the Lord will be the light thereof – Is. 66:22; 2 Pet. 3:12, 13; 1 Cor. 13:12; 1 jn. 3:2-3; Rev. 21:1-7 22:1-5.</p></li>
            <li><p>That <strong>Hell</strong> is a place of everlasting punishment where (all who do not have their names in the Book of Life) will suffer torments forever and ever. It was prepared for the devil and his angels (Mat. 25:41) but God has decreed that the wicked and those who forget Him and reject Jesus Christ will also be cast there because of their sins and neglect of his salvation. Ps. 9:17; Mat. 25:46; Luke 12:4, 5:16:19-31; mat. 5:22-30; Mark 9: 43-47; Rev. 14; 11; 20:10, 12-15.
                </p></li>
            </ul>
        </div>
        </section>
    )
}
